### ISSUE TITLE
Discuss _multimedia

### ISSUE THREAD

**Issue by 0xWDG** [wesdegroot/_.js#9]
`_multimedia` is the module that you want if you want to use multimedia.
See: [Wiki](https://github.com/wesdegroot/_.js/wiki/module_multimedia), [005/modules/_multimedia](https://github.com/wesdegroot/_.js/blob/master/005/modules/_multimedia.js), [005/modules/multimedia.html](https://github.com/wesdegroot/_.js/blob/master/005/modules/multimedia.html)

What it can do? [see it here]

**Comment by 0xWDG** [comment]
Todo:
- [x] Video test
- [x] Video test [before]
- [x] Video test [after]
- [x] Video test [multiple video's]
- [x] Switch video (ads etc.)
- [x] audio test
- [x] audio test [before]
- [x] audio test [after]
- [x] audio test [multiple audio files]
- [x] Multiple files (playlist)
- [x] Skip: `_('.myWrapper').mmPlayer_skip();`
- [x] Disable seek in before, and after (used for ads)

After test passed:
- [x] Release as final

**Comment by wesdegroot** [comment]
- [ ] Disable seek in before, and after (used for ads)
